name: Linux (Arm64)

on:
  pull_request:
  push:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-24.04-arm

    concurrency:
        group: ${{ github.ref }}-${{ github.base_ref }}-${{ github.head_ref }}-Ubuntu-Arm64
        cancel-in-progress: true
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: prepare local xmake
        run: cp -rf . ../xmake-source
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: local#../xmake-source

      - name: Prepare
        run: |
          sudo apt update
          sudo apt install -y unzip build-essential llvm libc++-dev

      - name: Tests
        run: |
          xmake lua -v -D tests/run.lua
          xrepo --version

